### ISSUE TITLE
Wallet extension crushed and show error.

### ISSUE THREAD

**Issue by imranmahmudshoiball** [argentlabs/argent-x#1538]
v5.0.12

{
  "stack": "TypeError: o.toUpperCase is not a function\n    at n (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:128:20508)\n    at a (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:128:20715)\n    at j (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1501:4551)\n    at ee (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:972:9648)\n    at Os (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2685:20885)\n    at El (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:3329)\n    at j1 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:47637)\n    at el (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:42239)\n    at xu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:42167)\n    at Zu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:42017)\n    at _i (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:38148)\n    at Ii (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:38994)\n    at Ee (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2685:3352)\n    at vc (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2687:39458)\n    at tt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2684:9176)\n    at ii (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2684:34002)\n    at la (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2684:17844)\n    at yn (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2684:17610)",
  "message": "o.toUpperCase is not a function",
  "__sentry_captured__": true
}

    at ee (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:972:8702)
    at je (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2713:4904)
    at dt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2713:8927)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:53621
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:5387
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:53621
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:5387
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:53621
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:5387
    at Ke
    at je (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2713:4904)
    at le (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2713:9622)
    at _e (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:141:5600)
    at Suspense
    at a (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:347:207)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:53621
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:5387
    at P (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:752:1442)
    at w (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3:58065)
    at z (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1:8289)
    at $ (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:53880)
    at J (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:6:3910)
    at vg (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3101:51)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3101:462
    at By (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3153:26362)
    at Yt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2743:6264)
    at ne (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2647:105)
    at P (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:104:2894)
    at v (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:104:2668)
    at j (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:104:3009)
    at qe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3175:6090)
    at P (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2519:86020)
    at D (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:131:29867)
    at ae (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2713:8994)
    at k (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:2704:3167)

**Comment by simonheys** [comment]
Thank you for reporting this issue, it should be fixed by #1533 which will be in a future release.
