### ISSUE TITLE
yarn setup error

### ISSUE THREAD

**Issue by forest21000** [argentlabs/argent-x#2024]
when I run yarn setup in cmd window in windows ,I got an error like this.

**E:\argent\argent-x>yarn setup
yarn run v1.22.19
$ yarn install --frozen-lockfile && yarn allow-scripts && husky install && patch-package && lerna run setup --stream
[1/4] Resolving packages...
warning Resolution field "@babel/plugin-transform-react-jsx@7.17.12" is incompatible with requested version "@babel/plugin-transform-react-jsx@^7.18.6"
warning Resolution field "@babel/preset-react@7.17.12" is incompatible with requested version "@babel/preset-react@^7.18.6"
warning Resolution field "@babel/plugin-transform-react-jsx@7.17.12" is incompatible with requested version "@babel/plugin-transform-react-jsx@^7.18.6"
success Already up-to-date.
$ E:\argent\argent-x\node_modules.bin\allow-scripts
E:\argent\argent-x\node_modules@lavamoat\allow-scripts\src\index.js:406
      const binsList = Object.entries(normalizeBin(depPackageJson)?.bin || {})
                                                                   ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (E:\argent\argent-x\node_modules@lavamoat\allow-scripts\src\cli.js:4:76)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.**

My OS is windows 10,node version is v12.18.3.

Please help me! Tks!

**Comment by forest21000** [comment]
I have solved the problem after I upgrade my nodejs to the latest version V18.16.0

**Comment by forest21000** [comment]
I am upgrading yarn,maybe it will work after I finish upgrade the yarn.Then I will tell you the result!

**Comment by forest21000** [comment]
The error now like this:

@argent/stack-router: src/StackScreen.tsx:17:11 - error TS2312: An interface can only extend an object type or intersection of object types with statically known members.
@argent/stack-router: 17   extends ComponentProps<typeof StackScreenContainer> {
@argent/stack-router:              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@argent/stack-router: src/StackScreen.tsx:24:3 - error TS2339: Property 'children' does not exist on type 'StackScreenProps'.
@argent/stack-router: 24   children,
@argent/stack-router:      ~~~~~~~~
@argent/stack-router: src/StackScreen.tsx:76:7 - error TS2322: Type 'Transition' is not assignable to type 'ResponsiveValue<Transition<string & {}>> | undefined'.
@argent/stack-router:   Type 'Orchestration & Repeat & Tween' is not assignable to type 'ResponsiveValue<Transition<string & {}>> | undefined'.
@argent/stack-router:     Type 'Orchestration & Repeat & Tween' is not assignable to type 'Partial<Record<string | (string & {}), Transition<string & {}>>>'.
@argent/stack-router:       Index signature for type 'string' is missing in type 'Orchestration & Repeat & Tween'.
@argent/stack-router: 76       transition={transition}
@argent/stack-router:          ~~~~~~~~~~
@argent/stack-router:   node_modules/@chakra-ui/styled-system/dist/index.d.ts:1570:5
@argent/stack-router:     1570     transition?: Token<CSS.Property.Transition>;
@argent/stack-router:              ~~~~~~~~~~
@argent/stack-router:     The expected type comes from property 'transition' which is declared here on type 'IntrinsicAttributes & Omit<HTMLAttributesWithoutMotionProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement> & MotionProps & RefAttributes<...>, "transition" | ... 418 more ... | "as"> & { ...; } & Omit<...> & { ...; }'
@argent/stack-router: src/presentation/getWrappedChildrenAndPresentation.tsx:76:20 - error TS2322: Type '{ children: any; path: string; }' is not assignable to type 'IntrinsicAttributes & StackScreenProps'.
@argent/stack-router:   Property 'children' does not exist on type 'IntrinsicAttributes & StackScreenProps'.
@argent/stack-router: 76         element = <StackScreen path={childPath}>{element}</StackScreen>
@argent/stack-router:                       ~~~~~~~~~~~
