### ISSUE TITLE
My wallet is not working!!!

### ISSUE THREAD

**Issue by creulean** [argentlabs/argent-x#2067]
v5.5.0

{
  "stack": "Error: 1688927689.567 can't be computed by felt()\n    at Je (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:662:102694)\n    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:664:6334\n    at Array.flatMap (<anonymous>)\n    at $t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:664:6115)\n    at Ce (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:664:6372)\n    at Ut.compile (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:664:6428)\n    at Ut.toCalldata (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:664:7153)\n    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:49972\n    at Array.map (<anonymous>)\n    at wO (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:49747)\n    at Xc (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:205:20679)\n    at Gu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:45916)\n    at Hu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:41498)\n    at ad (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:41426)\n    at iu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:41277)\n    at xu (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:37491)\n    at ju (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:207:36387)\n    at k (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:272:1535)\n    at MessagePort.R (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:272:1894)",
  "message": "1688927689.567 can't be computed by felt()",
  "__sentry_captured__": true
}

    at wO (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:48745)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:298:42244
    at form
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:298:42244
    at $m (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1039:13032)
    at LY (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:50988)
    at rC (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:53367)
    at pK (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:7027)
    at Z_ (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:6951)
    at Iq (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:67846)
    at Pq (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1253:68502)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at rse (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1481:9789)
    at Suspense
    at WL (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:919:18367)
    at e (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:919:18210)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18472
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:620:3187
    at $4 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:245:2463)
    at Z (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:617:4829)
    at S (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:617:3211)
    at U (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:1:18882)
    at z (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:617:545)
    at q (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:617:5317)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:617:5808
    at gS (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:3687:52759)
    at tr (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:276:6283)
    at kd (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:589:114)
    at w (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:123:9312)
    at K (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:123:9747)
    at I (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:123:9968)
    at Fe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:678:5988)
    at Tt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1493:14492)
    at dse (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1493:1179)
    at dt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:244:10331)
    at $ (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/238.js:235:3690)
      
<img width="377" alt="截屏2023-07-10 02 47 05" src="https://github.com/argentlabs/argent-x/assets/95141004/bf043a8d-027c-4acd-b232-218f7de15869">

**Comment by creulean** [comment]
After closing the Argent wallet extension, when I reopen it, I still cannot use it and the same issue persists!

**Comment by denispro2015** [comment]
same bro!!!!

**Comment by janek26** [comment]
we'll release a fix for this very soon, thanks for reporting! :)

**Comment by denispro2015** [comment]
Thanks lot))) I`ll wait)))

**Comment by 69relyT** [comment]
i have the same problems, also balance token says !error

**Comment by stuart-kieser** [comment]
I appear to have this issue now, when i click a button the wallet freezes?
