### ISSUE TITLE
Switching to Sepolia renders the wallet unuseable 

### ISSUE THREAD

**Issue by arijoon** [argentlabs/argent-x#2107]
After switching to Sepolia, the wallet can no longer be used:

```
v5.12.3

{
  "fileName": "moz-extension://cbd0c54d-c071-4676-9795-38620f7e3070/main.js",
  "lineNumber": 197,
  "columnNumber": 17634,
  "message": "can't access property \"includes\", c.possibleFeeTokenAddresses is undefined"
}
```

Seems like an invalid prop access. Please note that there is no way to switch the network and this effectively means wallet is perpetually locked

**Comment by milancermak** [comment]
Having the same issue. 

It would be helpful to do a hotfix release where we could dismiss the error screen and at least be allowed to switch back to mainnet or something similar to unblock the wallet.

Having a bricked wallet is no fun.

<img width="354" alt="Screenshot 2024-01-18 at 16 33 41" src="https://github.com/argentlabs/argent-x/assets/184055/19f65511-4fd9-43f0-9358-7f1662e899ea">

**Comment by eminmtas** [comment]
I am having this issue, too. Could someone from the team check for it please? I am unable to use my wallet and I don't want to reset it also because I don't know if I saved my seed phrases correctly.

Browser: Chrome
Browser version: 121.0.6167.140 (latest)
Argent X version: 5.12.8

Screenshot: 
![image](https://github.com/argentlabs/argent-x/assets/44838743/0487fff5-b206-42a5-bf01-3178df4faf4f)

Error Log:

```console
v5.12.8

{
  "stack": "TypeError: Cannot read properties of undefined (reading 'includes')\n    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:197:17662\n    at Array.filter (<anonymous>)\n    at Object.read (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:197:17624)",
  "message": "Cannot read properties of undefined (reading 'includes')"
}

    at i6 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:701:14850)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:301:42151
    at Suspense
    at O3 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:756:2801)
    at Oj (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:756:6325)
    at Mj (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:756:6081)
    at By (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:756:8057)
    at div
    at sn (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:2705:8062)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at Qm (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:83065)
    at x (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:246:4514)
    at At (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:246:10264)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at tO
    at div
    at sn (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:2705:8062)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at x (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:246:4514)
    at rt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:246:10962)
    at g (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:2705:152)
    at j (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:2705:971)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:301:42151
    at xf (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:81731)
    at Af (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:84441)
    at p0 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:81502)
    at oO (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:48302)
    at q0 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:5287:795)
    at Suspense
    at is (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:647:21547)
    at n (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:647:21400)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20372
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:623:3186
    at Pl (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:197:4147)
    at i (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:341:20440)
    at U (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:620:3169)
    at j (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:9:20793)
    at M (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:620:542)
    at Y (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:620:4547)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:620:5034
    at nR (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:5268:54281)
    at en (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:280:6282)
    at zA (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:527:105)
    at S (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:126:13655)
    at j (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:126:14090)
    at D (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:126:14311)
    at xe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:2731:6077)
    at hn (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:62983)
    at fO (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:1083:51777)
    at _t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:246:10331)
    at J (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/931.js:237:3690)
```

**Comment by JulianKingman** [comment]
I had the opposite problem: created a wallet under sepolia, it disappears when switching to mainnet.
