### ISSUE TITLE
Error: path should begin with baseDerivationPath

### ISSUE THREAD

**Issue by mtxmomoaudio** [argentlabs/argent-x#2148]
Tying to open my Argent wallet I havnt used in a while. Account 1 pops up, but when I hit the dropdown to switch between accounts I get this error:

v5.19.3

{
  "stack": "Error: path should begin with baseDerivationPath\n    at L (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:27:121393)\n    at qte (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:27855)\n    at Array.sort (<anonymous>)\n    at mut (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:28168)\n    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:32208\n    at Object.useMemo (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/599.js:19:23622)\n    at c.useMemo (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/599.js:37:6252)\n    at nne (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:31981)\n    at jut (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:32653)\n    at ji (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/599.js:19:17299)",
  "message": "path should begin with baseDerivationPath"
}

    at jut (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:471:32281)
    at Suspense
    at z0 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:447:9196)
    at Pve (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:4389)
    at aU (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:11084)
    at oce (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:539:41812)
    at tEt
    at Pve (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:4389)
    at aU (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:11084)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:1:12129
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:589:249261
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:27:125185
    at $q
    at sCt
    at Pve (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:4389)
    at cU (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:11768)
    at tnt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:442:9634)
    at cCt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:540:54898)
    at Suspense
    at z0 (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:447:9196)
    at uCt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:540:55994)
    at i (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:540:55856)
    at dI (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:389:11143)
    at sye (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:398:7598)
    at XLe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:414:28003)
    at HLe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:414:27162)
    at ZLe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:414:27778)
    at QLe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:414:27543)
    at EDe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:404:838589)
    at yCt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:540:57267)
    at ar (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:589:127240)
    at div
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:1:12129
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:589:249261
    at znt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:447:8597)
    at LN (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:75:7174)
    at cz (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:369:3059)
    at Xt (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:1:12416)
    at d5e (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:369:446)
    at v5e (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:369:4401)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:369:11380
    at N9t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:551:26881)
    at Pze (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:414:111336)
    at Or (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:2663:6198)
    at Ve (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:551:28559)
    at F9t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/651.js:551:26962)

**Comment by Angiepeck22** [comment]
Hello @mtxmomoaudio 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID ARG07638
Please see the link below to our dedicated support line:
[Argent wallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
