### ISSUE TITLE
Error in 4.1.7 by new a account

### ISSUE THREAD

**Issue by sunzheng1994** [argentlabs/argent-x#821]
QuotaExceededError: Failed to execute 'setItem' on 'Storage': Setting the value of 'accountMetadata' exceeded the quota.

v4.1.7

TypeError: t.replace is not a function

    at t.ErrorScreen (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1448551)
    at q (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993159)
    at div
    at A (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1174447)
    at div
    at A (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1174447)
    at Y
    at X (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993774)
    at t.AppRoutes (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1238475)
    at Suspense
    at t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1250315)
    at oe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281569)
    at ie (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281310)
    at ae (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281702)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1186824
    at t.App (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1230788)
    at J (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993215)
    at ie (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:994707)

**Comment by dhruvkelawala** [comment]
We updated the wallet, this issue is no longer relevant.
