### ISSUE TITLE
wallet erors new version

### ISSUE THREAD

**Issue by BangArmoy** [argentlabs/argent-x#822]
v4.1.7

Error: Invalid character

    at t.DefaultTransactionDetails (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1459433)
    at t.TransactionItem (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1458271)
    at t.TransactionsList (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1458078)
    at form
    at A (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1174447)
    at t.ConfirmScreen (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1444434)
    at t.ApproveTransactionScreen (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1440475)
    at t.ActionScreen (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1424978)
    at q (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993159)
    at div
    at A (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1174447)
    at div
    at A (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1174447)
    at Y
    at X (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993774)
    at t.AppRoutes (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1238475)
    at Suspense
    at t (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1250315)
    at oe (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281569)
    at ie (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281310)
    at ae (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:432:281702)
    at chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1186824
    at t.App (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:1230788)
    at J (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:993215)
    at ie (chrome-extension://dlcobpjiigpikoobohmabehhmhfoodbb/main.js:630:994707)

**Comment by dhruvkelawala** [comment]
We updated the wallet, this issue is no longer relevant.
